# Generated by Django 5.2.8 on 2025-12-06 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('optimal_temp_min', models.IntegerField()),
                ('optimal_temp_max', models.IntegerField()),
                ('rainfall_min', models.IntegerField(help_text='Minimum annual rainfall in mm')),
                ('rainfall_max', models.IntegerField(help_text='Maximum annual rainfall in mm')),
                ('soil_types', models.CharField(help_text='Comma-separated soil types', max_length=200)),
                ('planting_season', models.CharField(max_length=100)),
                ('harvest_period', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='crops/')),
            ],
        ),
        migrations.CreateModel(
            name='PlantingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('optimal_planting_start', models.DateField()),
                ('optimal_planting_end', models.DateField()),
                ('days_to_harvest', models.IntegerField()),
                ('care_instructions', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence_score'],
            },
        ),
    ]
